-module(yate_message_SUITE).

-compile(export_all).

-include("../include/yate.hrl").

all() ->
    [
     create_an_empty_yate_message,
     create_a_named_yate_message,
     create_a_named_yate_message_with_params,
     create_a_named_yate_message_with_params_and_retvalue,
     get_yate_message_id,
     get_yate_message_time,
     get_yate_message_name,
     get_yate_message_retvalue,
     get_yate_message_param_value,
     change_yate_message_id,
     change_yate_message_time,
     change_yate_message_name,
     change_yate_message_retvalue,
     change_yate_message_param_value,
     
     check_is_processed,
     set_processed
    ].

create_an_empty_yate_message(_Config) ->
    EmptyYateMessage = yate_message:new(),
    is_record(EmptyYateMessage, yate_event),
    yate_event:is_message(EmptyYateMessage),
    % autogenerated id and time attributes should not be empty
    true = ([] =/= yate_message:id(EmptyYateMessage)),
    true = ([] =/= yate_message:time(EmptyYateMessage)),
    % name should be empty
    [] = yate_message:name(EmptyYateMessage).

create_a_named_yate_message(_Config) ->
    NamedYateMessage = yate_message:new("call.route"),
    "call.route" = yate_message:name(NamedYateMessage).

create_a_named_yate_message_with_params(_Config) ->
    YateMessage = yate_message:new("call.route",[{chan_id, "sip/1"}]),
    "sip/1" = yate_message:param(chan_id, YateMessage).
    
create_a_named_yate_message_with_params_and_retvalue(_Config) ->
    YateMessage = yate_message:new("call.route",[{chan_id, "sip/1"}], "retvalue123"),
    "retvalue123" = yate_message:retvalue(YateMessage).
    
get_yate_message_id(_Config) ->
    YateMessage = yate_message:new("call.route"),
    [] =/= yate_message:id(YateMessage).

get_yate_message_time(_Config) ->
    YateMessage = yate_message:new("call.route"),
    [] =/= yate_message:time(YateMessage).

get_yate_message_name(_Config) ->
    YateMessage = yate_message:new("call.route"),
    [] =/= yate_message:name(YateMessage).

get_yate_message_retvalue(_Config) ->
    YateMessage = yate_message:new("call.route",[{chan_id, "sip/1"}], "retvalue123"),
    [] =/= yate_message:retvalue(YateMessage).

get_yate_message_param_value(_Config) ->
    YateMessage = yate_message:new("call.route",[{chan_id, "sip/1"}], "retvalue123"),
    [] =/= yate_message:param(chan_id, YateMessage).
    
change_yate_message_id(_Config) ->
    YateMessage = yate_message:new("call.route",[{chan_id, "sip/1"}], "retvalue123"),
    YateMessageChangedId = yate_message:id("changedid123", YateMessage),
    "changedid123" = yate_message:id(YateMessageChangedId).

change_yate_message_time(_Config) ->
    YateMessage = yate_message:new("call.route",[{chan_id, "sip/1"}], "retvalue123"),
    YateMessageChangedTime = yate_message:time("12312412411", YateMessage),
    "12312412411" = yate_message:time(YateMessageChangedTime).    

change_yate_message_name(_Config) ->
    YateMessage = yate_message:new("call.route",[{chan_id, "sip/1"}], "retvalue123"),
    YateMessageChangedName = yate_message:name("call.execute", YateMessage),
    "call.execute" = yate_message:name(YateMessageChangedName).    

change_yate_message_retvalue(_Config) ->
    YateMessage = yate_message:new("call.route",[{chan_id, "sip/1"}], "retvalue123"),
    YateMessageChangedRetValue = yate_message:retvalue("retvalue456", YateMessage),
    "retvalue456" = yate_message:retvalue(YateMessageChangedRetValue).    

change_yate_message_param_value(_Config) ->
    YateMessage = yate_message:new("call.route",[{chan_id, "sip/1"}], "retvalue123"),
    YateMessageChangedParam = yate_message:param(chan_id, "sip/2", YateMessage),
    "sip/2" = yate_message:param(chan_id, YateMessageChangedParam).    

check_is_processed(_Config) ->    
    % New message are not processed by default
    YateMessage = yate_message:new("call.route",[{chan_id, "sip/1"}], "retvalue123"),
    false = yate_message:is_processed(YateMessage).
    
set_processed(_Config) ->
    YateMessage = yate_message:new("call.route",[{chan_id, "sip/1"}], "retvalue123"),
    YateMessage2 = yate_message:set_processed(YateMessage),
    true = yate_message:is_processed(YateMessage2),
    YateMessage3 = yate_message:set_processed(false, YateMessage),
    false = yate_message:is_processed(YateMessage3),
    YateMessage4 = yate_message:set_processed("false", YateMessage),
    false = yate_message:is_processed(YateMessage4),
    YateMessage5 = yate_message:set_processed("true", YateMessage),
    true = yate_message:is_processed(YateMessage5),
    YateMessage6 = yate_message:set_processed(true, YateMessage),
    true = yate_message:is_processed(YateMessage6).

    
