REBAR=./build-tools/rebar
YATERL_DEVTOOL=./build-tools/yaterl-devtool
PACK_YATERL=-y deps/yaterl --pack-yaterl 

help:
	@echo "YATErl building tool."
	@echo "Usage: "
	@echo "       ./make {compile|clean}"        
	@echo
	@echo "       ./make pack"  
	@echo

compile: FORCE
	mkdir -p ./builds/
	${REBAR} get-deps 
	${REBAR} compile
	${YATERL_DEVTOOL} ${PACK_YATERL} pack ./builds/{{ project_name }}.escript {{ project_name }}

clean:
	${REBAR} clean

FORCE:
