#!/usr/bin/env escript
%% -*- erlang -*-

-module(pack).

-export([main/1]).

main(_) ->
    Files1 = load_files("*", "ebin"),
    Files2 = load_files("*", "deps/getopt/ebin"),
    Files3 = load_files("*", "deps/erlydtl/ebin"),
    Files = Files1 ++ Files2 ++ Files3,

    case zip:create("mem", Files, [memory]) of
        {ok, {"mem", ZipBin}} ->
            Script = <<"#!/usr/bin/env escript\n",
                       "%%!-sname yaterl_devtool -noinput\n", 
                       ZipBin/binary>>,
            
            case file:write_file("bin/yaterl_devtool", Script) of
                ok ->
                    ok;
                {error, WriteError} ->
                    io:format("Failed to write yaterl_devtool script: ~p\n", [WriteError]),
                    halt(1)
            end;
        {error, ZipError} ->
            io:format("Failed to construct yaterl_devtool script archive: ~p\n", [ZipError]),
            halt(1)
    end,

    %% Finally, update executable perms for our script
    [] = os:cmd("chmod a+x bin/yaterl_devtool").

load_files(Wildcard, Dir) ->
    [read_file(Filename, Dir) || Filename <- filelib:wildcard(Wildcard, Dir)].

read_file(Filename, Dir) ->
    {ok, Bin} = file:read_file(filename:join(Dir, Filename)),
    {Filename, Bin}.
